"""Type stubs for the compiled `rustai._rustai` extension."""

from typing import Any, Literal, Sequence

__version__: str

UnitKind = Literal["heading", "paragraph", "list_item", "code", "quote", "table"]

class RustaiError(Exception):
    """Base class for every rustai error."""

class NetworkError(RustaiError):
    """The request failed at the transport level."""

class HttpStatusError(RustaiError):
    """The server answered with a failure status."""

class RobotsError(RustaiError):
    """robots.txt disallows this URL."""

class ExtractError(RustaiError):
    """The document could not be parsed."""

class ProviderError(RustaiError):
    """A search provider failed."""

class BrowserError(RustaiError):
    """The headless fallback was unavailable."""

class Meta:
    @property
    def title(self) -> str | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def byline(self) -> str | None: ...
    @property
    def published(self) -> str | None: ...
    @property
    def language(self) -> str | None: ...
    @property
    def canonical(self) -> str | None: ...
    @property
    def site_name(self) -> str | None: ...
    def to_dict(self) -> dict[str, Any]: ...

class Unit:
    @property
    def kind(self) -> UnitKind: ...
    @property
    def level(self) -> int: ...
    @property
    def text(self) -> str: ...
    @property
    def markdown(self) -> str: ...
    @property
    def heading_path(self) -> list[str]: ...
    @property
    def position(self) -> int: ...
    @property
    def tokens(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

class DenoiseStats:
    @property
    def nodes_visited(self) -> int: ...
    @property
    def nodes_dropped(self) -> int: ...
    @property
    def html_bytes(self) -> int: ...
    @property
    def markdown_bytes(self) -> int: ...
    @property
    def compression(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

class Article:
    @property
    def url(self) -> str | None: ...
    @property
    def title(self) -> str | None: ...
    @property
    def markdown(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def meta(self) -> Meta: ...
    @property
    def units(self) -> list[Unit]: ...
    @property
    def stats(self) -> DenoiseStats: ...
    @property
    def tokens(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __len__(self) -> int: ...

class Page:
    @property
    def url(self) -> str: ...
    @property
    def final_url(self) -> str: ...
    @property
    def status(self) -> int: ...
    @property
    def content_type(self) -> str | None: ...
    @property
    def body(self) -> str: ...
    @property
    def elapsed_ms(self) -> int: ...
    @property
    def rendered(self) -> bool: ...
    def extract(self) -> Article: ...
    def to_dict(self) -> dict[str, Any]: ...

class SearchResult:
    @property
    def title(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def snippet(self) -> str: ...
    @property
    def providers(self) -> list[str]: ...
    @property
    def score(self) -> float: ...
    @property
    def rank(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

class Context:
    @property
    def query(self) -> str: ...
    @property
    def markdown(self) -> str: ...
    @property
    def tokens(self) -> int: ...
    @property
    def sources(self) -> list[dict[str, Any]]: ...
    @property
    def selected(self) -> list[dict[str, Any]]: ...
    @property
    def units_considered(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __str__(self) -> str: ...

class Research:
    @property
    def query(self) -> str: ...
    @property
    def context(self) -> Context: ...
    @property
    def markdown(self) -> str: ...
    @property
    def results(self) -> list[SearchResult]: ...
    @property
    def articles(self) -> list[Article]: ...
    @property
    def failures(self) -> list[tuple[str, str]]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __str__(self) -> str: ...

class Client:
    def __init__(
        self,
        *,
        providers: Sequence[str] | None = None,
        concurrency: int = 16,
        timeout: float = 20.0,
        impersonate: str = "chrome",
        respect_robots: bool = True,
        per_host_delay: float = 0.25,
        retries: int = 2,
        max_body_bytes: int = 8388608,
        accept_language: str = "en-US,en;q=0.9",
        browser_fallback: bool = False,
        contact_email: str | None = None,
        max_tokens: int = 2048,
        diversity: float = 0.35,
        include_links: bool = True,
        include_images: bool = False,
        include_tables: bool = True,
        limit: int = 10,
    ) -> None: ...
    def search(self, query: str, *, strict: bool = False) -> list[SearchResult]: ...
    def fetch(
        self, urls: Sequence[str], *, raise_on_error: bool = False
    ) -> list[Page]: ...
    def read(
        self, urls: Sequence[str], *, raise_on_error: bool = False
    ) -> list[Article]: ...
    def research(self, query: str, *, max_sources: int = 5) -> Research: ...

def extract(
    html: str,
    url: str | None = None,
    *,
    include_links: bool = True,
    include_images: bool = False,
    include_tables: bool = True,
) -> Article: ...
def extract_many(
    documents: Sequence[str],
    urls: Sequence[str | None] | None = None,
    *,
    include_links: bool = True,
    include_images: bool = False,
    include_tables: bool = True,
) -> list[Article]: ...
def slim(
    query: str,
    articles: Sequence[Article],
    *,
    max_tokens: int = 2048,
    diversity: float = 0.35,
    max_tokens_per_source: int | None = None,
    include_breadcrumbs: bool = True,
) -> Context: ...
def research(
    query: str,
    *,
    max_sources: int = 5,
    max_tokens: int = 2048,
    providers: Sequence[str] | None = None,
    impersonate: str = "chrome",
    respect_robots: bool = True,
    contact_email: str | None = None,
) -> Research: ...
def count_tokens(text: str) -> int: ...
def tokenize(text: str) -> list[str]: ...
def density(text: str) -> float: ...
def canonical_url(url: str) -> str | None: ...
def parse_feed(xml: str) -> list[dict[str, Any]]: ...
def parse_sitemap(xml: str) -> dict[str, list[str]]: ...
